#!/bin/bash
KNOWN_DEVICES_FILE="./known_devices.txt"
CURRENT_DEVICES_FILE="./current_devices.txt"
NEW_DEVICES_FILE="./new_devices.txt"

INTERFACES=("enp1s0" "enp2s0" "enp3s0" "enp4s0")

> "$CURRENT_DEVICES_FILE"

for iface in "${INTERFACES[@]}"; do
    ip neigh show dev "$iface"  >> "$CURRENT_DEVICES_FILE"
done

grep -oE '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}' "$CURRENT_DEVICES_FILE" > "$CURRENT_DEVICES_FILE.macs"

comm -23 <(sort "$CURRENT_DEVICES_FILE.macs") <(sort "$KNOWN_DEVICES_FILE") > "$NEW_DEVICES_FILE"

if [ -s "$NEW_DEVICES_FILE" ]; then
    cat "$NEW_DEVICES_FILE"
    cat "$CURRENT_DEVICES_FILE.macs" >> "$KNOWN_DEVICES_FILE"
fi

rm "$CURRENT_DEVICES_FILE.macs"
